### ISSUE TITLE
 ViewException In Distpicker.php line 104 :

### ISSUE THREAD

**Issue by userfhy** [laravel-admin-extensions/china-distpicker#27]
PHP version  PHP/7.4.7
Laravel version  6.18.38
Laravel Admin Version   1.8.4

```
 ViewException In Distpicker.php line 104 :
  Call to a member function with() on string (View: /www/localhost/blog/vendor/encore/laravel-admin/resources/views/form.blade.php)


#0 /www/localhost/blog/vendor/encore/laravel-admin/src/../resources/views/form.blade.php(31): Encore\ChinaDistpicker\Distpicker->render()
#1 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(43): include('/www/localhost/...')
#2 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('/www/localhost/...', Array)
#3 /www/localhost/blog/vendor/facade/ignition/src/Views/Engines/CompilerEngine.php(36): Illuminate\View\Engines\CompilerEngine->get('/www/localhost/...', Array)
#4 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/View/View.php(143): Facade\Ignition\Views\Engines\CompilerEngine->get('/www/localhost/...', Array)
#5 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/View/View.php(126): Illuminate\View\View->getContents()
#6 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\View\View->renderContents()
#7 /www/localhost/blog/vendor/encore/laravel-admin/src/Form/Builder.php(673): Illuminate\View\View->render()
#8 /www/localhost/blog/vendor/encore/laravel-admin/src/Form.php(1402): Encore\Admin\Form\Builder->render()
#9 /www/localhost/blog/vendor/encore/laravel-admin/src/Layout/Column.php(100): Encore\Admin\Form->render()
#10 /www/localhost/blog/vendor/encore/laravel-admin/src/Layout/Row.php(80): Encore\Admin\Layout\Column->build()
#11 /www/localhost/blog/vendor/encore/laravel-admin/src/Layout/Content.php(215): Encore\Admin\Layout\Row->build()
#12 /www/localhost/blog/vendor/encore/laravel-admin/src/Layout/Content.php(308): Encore\Admin\Layout\Content->build()
#13 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/Http/Response.php(42): Encore\Admin\Layout\Content->render()
#14 /www/localhost/blog/vendor/symfony/http-foundation/Response.php(205): Illuminate\Http\Response->setContent(Object(Encore\Admin\Layout\Content))
#15 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/Routing/Router.php(749): Symfony\Component\HttpFoundation\Response->__construct(Object(Encore\Admin\Layout\Content), 200, Array)
#16 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\Routing\Router::toResponse(Object(Illuminate\Http\Request), Object(Encore\Admin\Layout\Content))
#17 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Encore\Admin\Layout\Content))
#18 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /www/localhost/blog/vendor/encore/laravel-admin/src/Middleware/Permission.php(46): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Encore\Admin\Middleware\Permission->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 /www/localhost/blog/vendor/encore/laravel-admin/src/Middleware/Bootstrap.php(15): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Encore\Admin\Middleware\Bootstrap->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /www/localhost/blog/vendor/encore/laravel-admin/src/Middleware/LogOperation.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Encore\Admin\Middleware\LogOperation->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /www/localhost/blog/vendor/encore/laravel-admin/src/Middleware/Pjax.php(24): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Encore\Admin\Middleware\Pjax->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /www/localhost/blog/vendor/encore/laravel-admin/src/Middleware/Authenticate.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Encore\Admin\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#43 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#44 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#45 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#46 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#47 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#48 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#56 /www/localhost/blog/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#60 /www/localhost/blog/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#61 /www/localhost/blog/public/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#62 {main}
```

**Comment by nicesome** [comment]
我也有这个问题，laravel 6、laravel-admin v1.8

**Comment by gnever** [comment]
laravel 回退个版本或者把
```vendor/encore/laravel-admin/src/Form/Field.php``` 的 render() 方法内的 
```//return Admin::component($this->getView(), $this->variables());```
改为
```return view($this->getView(), $this->variables());```

**Comment by z-song** [comment]
这个问题已经修复了。

**Comment by terranc** [comment]
在什么版本修复了？

**Comment by songlen** [comment]
laravel-admin 1.8.10 
地区插件版本 1.4 依然报这个错
